In [1]:
from typing import Literal

import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import scanpy as sc
import spatialdata_io
import spatialdata_plot
import squidpy as sq
import spatialdata as sd

from anndata import AnnData
from spatialdata import SpatialData
from spatialdata._core.query.relational_query import _get_unique_label_values_as_index
from spatialdata.datasets import blobs
from spatialdata.models import TableModel
from spatialdata.transformations import Affine, set_transformation
from spatialdata_io.experimental import from_legacy_anndata, to_legacy_anndata
sdata = sd.read_zarr("dati/c26t16/c26t16_align1.zarr")

sdata

SpatialData object with:
├── Images
│     ├── 'C26T16_GFP': MultiscaleSpatialImage[cyx] (3, 10780, 11486), (3, 5389, 5742), (3, 2694, 2870), (3, 1347, 1434), (3, 673, 716)
│     ├── 'C26T16_WGA': MultiscaleSpatialImage[cyx] (3, 10780, 11486), (3, 5389, 5742), (3, 2694, 2870), (3, 1347, 1434), (3, 673, 716)
│     ├── 'C26T16_dapi': MultiscaleSpatialImage[cyx] (3, 10780, 11486), (3, 5389, 5742), (3, 2694, 2870), (3, 1347, 1434), (3, 673, 716)
│     ├── 'C26T16_full_image': MultiscaleSpatialImage[cyx] (3, 15273, 14901), (3, 7636, 7450), (3, 3818, 3725), (3, 1909, 1862), (3, 954, 931)
│     └── 'C26T16_merge': MultiscaleSpatialImage[cyx] (3, 10780, 11486), (3, 5389, 5742), (3, 2694, 2870), (3, 1347, 1434), (3, 673, 716)
├── Shapes
│     └── 'C26T16': GeoDataFrame shape: (1239, 2) (2D shapes)
└── Tables
      └── 'table': AnnData (1239, 19465)
with coordinate systems:
▸ 'aligned', with elements:
        C26T16_GFP (Images), C26T16_WGA (Images), C26T16_dapi (Images), C26T16_full_image (Images), C26T16_merge (Images), C26T16 (Shapes)

Cerca l'espressione genica

In [2]:
sdata.table

/tmp/ipykernel_73231/3174552237.py:1: DeprecationWarning: Table accessor will be deprecated with SpatialData version 0.1, use sdata.tables instead.
  sdata.table

AnnData object with n_obs × n_vars = 1239 × 19465
    obs: 'in_tissue', 'array_row', 'array_col', 'spot_id', 'region'
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'spatial', 'spatialdata_attrs'
    obsm: 'spatial'

In [5]:
sdata.table.to_df()["Foxo1"].mean()

/tmp/ipykernel_73231/2258252379.py:1: DeprecationWarning: Table accessor will be deprecated with SpatialData version 0.1, use sdata.tables instead.
  sdata.table.to_df()["Foxo1"].mean()

1.2033899

In [59]:
x = sdata.table.to_df()

/tmp/ipykernel_141441/2422175384.py:1: DeprecationWarning: Table accessor will be deprecated with SpatialData version 0.1, use sdata.tables instead.
  x = sdata.table.to_df()

In [4]:
x.to_csv(("dati/csv/c26t16_gene.csv"))

NameError: name 'x' is not defined

In [63]:
x

,Xkr4,Rp1,Sox17,Lypla1,Tcea1,Rgs20,Atp6v1h,Oprk1,Npbwr1,Rb1cc1,...,Uba1y,Kdm5d,Eif2s3y,Uty,Ddx3y,Zfy2,Sry,Gm4064,Gm3376,Gm20830
AAACAGGGTCTATATT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACAGTGTTCCTGGG-1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
AAACCGGGTAGGTACC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCGTTCGTCCAGG-1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAGACGGTTGAT-1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTTGGCAATGACTG-1,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTGTTGTGTGTCAAGA-1,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0
TTGTTTCACATCCAGG-1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0
TTGTTTCCATACAACT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTGTTTGTATTACACG-1,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [64]:
y = x.transpose()

In [65]:
y.describe().transpose()["max"].describe()

count    1239.000000
mean      368.018563
std       216.802790
min         9.000000
25%       217.000000
50%       343.000000
75%       479.000000
max      1414.000000
Name: max, dtype: float64

# Ricorda
Ricorda di aggiungere questo quando estraggo i colori

In [67]:
sdata["C26T16"]

                       geometry     radius
0     POINT (6417.000 3244.000)  55.512907
1     POINT (2652.000 5949.000)  55.512907
2     POINT (7207.000 4496.000)  55.512907
3     POINT (5767.000 5747.000)  55.512907
4     POINT (8410.000 8810.000)  55.512907
...                         ...        ...
1234  POINT (2165.000 4856.000)  55.512907
1235  POINT (8998.000 8617.000)  55.512907
1236  POINT (4876.000 5780.000)  55.512907
1237  POINT (6759.000 4428.000)  55.512907
1238  POINT (2646.000 5778.000)  55.512907

[1239 rows x 2 columns]

In [66]:
sdata.table.obsm["spatial"]

/tmp/ipykernel_141441/638507763.py:1: DeprecationWarning: Table accessor will be deprecated with SpatialData version 0.1, use sdata.tables instead.
  sdata.table.obsm["spatial"]

array([[6417, 3244],
       [2652, 5949],
       [7207, 4496],
       ...,
       [4876, 5780],
       [6759, 4428],
       [2646, 5778]])

In [68]:
rename_dict = {"aligned": "global"}
sdata.rename_coordinate_systems(rename_dict)
adata = to_legacy_anndata(sdata, include_images=True)

/home/stefano/.local/lib/python3.10/site-packages/spatialdata/_core/query/relational_query.py:325: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  groups_df = table.obs.groupby(by=region_column_name)

WARNING  The vector part of the transformation matrix is not isotropic, the radius will be scaled by the average of
         the modules of eigenvalues of the affine transformation matrix.
         matrix=[[ 0.1309479   0.         19.74532707]
          [ 0.          0.13095004  0.        ]
          [ 0.          0.          1.        ]]
         eigenvalues=[0.1309479  0.13095004]
         scale_factor=0.13094897178383064
WARNING  The vector part of the transformation matrix is not isotropic, the radius will be scaled by the average of
         the modules of eigenvalues of the affine transformation matrix.
         matrix=[[0.03926444 0.         5.92059274]
          [0.         0.03928501 0.        ]
          [0.         0.         1.        ]]
         eigenvalues=[0.03926444 0.03928501]
         scale_factor=0.039274725941465104

In [73]:
adata.obsm["spatial"]

array([[860.03800784, 424.80193806],
       [367.01916054, 779.02180318],
       [963.48684964, 588.75139134],
       ...,
       [658.24729239, 756.89124599],
       [904.82218999, 579.84678845],
       [366.23347314, 756.6293459 ]])